### ISSUE TITLE
PHP Warning, Not Updating

### ISSUE THREAD

**Issue by sewmyheadon** [markjaquith/WordPress-Plugin-Directory-Slurper#9]
Hey Mark,

Thanks for this code!

My initial _slurp_ went just fine, but I just tried to run an update several times and am not sure what's wrong.  I'm using the latest code from the git repo.

Here's what I get when updating:

> [eric@ea-fedora WordPress-Plugin-Directory-Slurper]$ sudo ./update
> Determining most recent SVN revision...
> Most recent SVN revision: 725464
> Last synced revision: 678503
> PHP Warning:  file_get_contents(http://plugins.trac.wordpress.org/log/?
> verbose=on&mode=follow_copy&format=changelog&rev=725464&limit=46961): failed to > open stream: HTTP request failed!  in /home/eric/Dropbox/dev/vhost/WordPress-Plugin-
> Directory-Slurper/update on line 57
> [CLEANUP] Updated plugins/.last-revision to 725464
> [SUCCESS] Done updating plugins!
> It took 1 minutes and 23 seconds to update 0 plugins
> [DONE]

It's probably been about two months since the original _slurp_, which went flawlessly and I have never yet updated (or tried).

**Comment by iandunn** [comment]
FYI @kovshenin, this impacts the theme dir slurper too. I get this error there when trying to pull more than `~500` revisions.

**Comment by joemcgill** [comment]
Just ran into this issue as well. The real fun part is that even after the failure, the `plugins/.last-revision`file gets updated to the latest changeset, which can lead to mismatched plugins if you're not paying attention.

**Comment by iandunn** [comment]
@markjaquith, I'm guessing you don't have time to review PRs for this repo anymore, so what do you think about just rubber-stamping a merge of #14 from @DrewAPicture? I tested it and it worked for me, even after almost 2 years without running an update.

**Comment by DrewAPicture** [comment]
@iandunn fwiw, I always thought some combination of #12 and #14 would be the way to go.

**Comment by iandunn** [comment]
Yeah, I think that one should be merged too, but it seems like one of them will need to be done first, then the other will have to be rebased before merging.

I think #14 would be better to merge first, since the script is basically broken without it. #12 is more of an enhancement to speed things up.

#18 would also be a big performance improvement, but would also need to be rebased after #12 is merged.

**Comment by nylen** [comment]
#25 should fix everything discussed in this issue.  Please take a look if you are using this tool.
